/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/signUp'
import { Route as LandingpageRouteImport } from './routes/landingpage'
import { Route as AuthenticationtitleRouteImport } from './routes/authenticationtitle'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PokemonCardPokemonCardRouteImport } from './routes/pokemonCard/PokemonCard'

const SignUpRoute = SignUpRouteImport.update({
  id: '/signUp',
  path: '/signUp',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingpageRoute = LandingpageRouteImport.update({
  id: '/landingpage',
  path: '/landingpage',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticationtitleRoute = AuthenticationtitleRouteImport.update({
  id: '/authenticationtitle',
  path: '/authenticationtitle',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PokemonCardPokemonCardRoute = PokemonCardPokemonCardRouteImport.update({
  id: '/pokemonCard/PokemonCard',
  path: '/pokemonCard/PokemonCard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/authenticationtitle': typeof AuthenticationtitleRoute
  '/landingpage': typeof LandingpageRoute
  '/signUp': typeof SignUpRoute
  '/pokemonCard/PokemonCard': typeof PokemonCardPokemonCardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/authenticationtitle': typeof AuthenticationtitleRoute
  '/landingpage': typeof LandingpageRoute
  '/signUp': typeof SignUpRoute
  '/pokemonCard/PokemonCard': typeof PokemonCardPokemonCardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/authenticationtitle': typeof AuthenticationtitleRoute
  '/landingpage': typeof LandingpageRoute
  '/signUp': typeof SignUpRoute
  '/pokemonCard/PokemonCard': typeof PokemonCardPokemonCardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/authenticationtitle'
    | '/landingpage'
    | '/signUp'
    | '/pokemonCard/PokemonCard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/authenticationtitle'
    | '/landingpage'
    | '/signUp'
    | '/pokemonCard/PokemonCard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/authenticationtitle'
    | '/landingpage'
    | '/signUp'
    | '/pokemonCard/PokemonCard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthenticationtitleRoute: typeof AuthenticationtitleRoute
  LandingpageRoute: typeof LandingpageRoute
  SignUpRoute: typeof SignUpRoute
  PokemonCardPokemonCardRoute: typeof PokemonCardPokemonCardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signUp': {
      id: '/signUp'
      path: '/signUp'
      fullPath: '/signUp'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landingpage': {
      id: '/landingpage'
      path: '/landingpage'
      fullPath: '/landingpage'
      preLoaderRoute: typeof LandingpageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authenticationtitle': {
      id: '/authenticationtitle'
      path: '/authenticationtitle'
      fullPath: '/authenticationtitle'
      preLoaderRoute: typeof AuthenticationtitleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokemonCard/PokemonCard': {
      id: '/pokemonCard/PokemonCard'
      path: '/pokemonCard/PokemonCard'
      fullPath: '/pokemonCard/PokemonCard'
      preLoaderRoute: typeof PokemonCardPokemonCardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthenticationtitleRoute: AuthenticationtitleRoute,
  LandingpageRoute: LandingpageRoute,
  SignUpRoute: SignUpRoute,
  PokemonCardPokemonCardRoute: PokemonCardPokemonCardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
